Lives
InfinityHackathon/game1 pull request #27
Opened 2022-01-16 21:13 UTC by KoldunovIvan

Добавил 3 жизни, и проигрыш при количестве жизней равному - 0

2022-01-29 09:48 UTC, ilyar requested changes

2022-01-29 09:48 UTC, ilyar commented on index.html
> +  if (score === brick) {
вне игрового цила

2022-01-29 09:48 UTC, ilyar commented on index.html
> +  if (score === brick) {
вне игрового цила

2022-01-29 09:48 UTC, ilyar commented on index.html
> +  bricks[c] = [];
отступы

2022-02-05 09:30 UTC, ilyar approved these changes

2022-02-05 09:36 UTC, merged

2022-02-05 13:54 UTC, den-kuznetsov commented
это интересно, но я бы на твоем месте делал бы красным не шарик, а фон. попробуй, может прикольно вийти.